/*
** mod_wiki.c - Git based wiki system for Apache module
** Copyright (C) 2011 Tsukasa Hamano <code@cuspy.org>
**
**  [Autogenerated via ``apxs -n wiki -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory
**  by running:
**
**    $ apxs -c -i mod_wiki.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /wiki in as follows:
**
**    #   httpd.conf
**    LoadModule wiki_module modules/mod_wiki.so
**    <Location />
**      SetHandler wiki
**      WikiRepository /path/to/repository.git
**      WikiName "My Wiki"
**      WikiCss /style.css
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /wiki and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**
**    The sample page from mod_wiki.c
*/

#include <sys/stat.h>

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "ap_config.h"
#include "apr_strings.h"

#include "git2.h"
#include "markdown.h"
#include "mod_wiki.h"

module AP_MODULE_DECLARE_DATA wiki_module;

extern char *mkd_doc_title(Document *);

static void markdown_output(Document * doc, request_rec * r)
{
    char *title;
    int ret;
    int size;
    char *p;
    wiki_conf *conf;
    list_t *css;

    conf =
        (wiki_conf *) ap_get_module_config(r->per_dir_config,
                                           &wiki_module);

    ret = mkd_compile(doc, MKD_TOC | MKD_AUTOLINK);
    ap_rputs("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n", r);
    ap_rputs("<!DOCTYPE html PUBLIC \n"
             "          \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n"
             "          \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n",
             r);
    ap_rputs("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n", r);
    ap_rputs("<head>\n", r);

    if (conf->css) {
        ap_rputs("<meta http-equiv=\"Content-Type\""
                 " content=\"text/html; charset=UTF-8\" />\n", r);
        ap_rputs("<meta http-equiv=\"Content-Style-Type\""
                 " content=\"text/css\" />\n", r);
        css = conf->css;
        do {
            ap_rprintf(r,
                       "<link rel=\"stylesheet\" href=\"%s\""
                       " type=\"text/css\" />\n", (char *)css->data);
            css = (list_t *) css->next;
        }
        while (css);
    }
    title = mkd_doc_title(doc);
    if (title) {
        if (conf->name) {
            ap_rprintf(r, "<title>%s - %s</title>\n", title, conf->name);
        } else {
            ap_rprintf(r, "<title>%s</title>\n", title);
        }
    }
    ap_rputs("</head>\n", r);
    ap_rputs("<body>\n", r);
    if (title) {
        ap_rprintf(r, "<h1 class=\"title\">%s</h1>\n", title);
    }
    if (conf->name) {
        ap_rprintf(r,
                   "<div class=\"subtitle\">" "From %s" "</div>\n",
                   conf->name);
    }
    if ((size = mkd_document(doc, &p)) != EOF) {
        ap_rwrite(p, size, r);
    }
    ap_rputc('\n', r);
    ap_rputs("</body>\n", r);
    ap_rputs("</html>\n", r);
    mkd_cleanup(doc);
}

static void log_oid(request_rec *r,
                    const char *name,
                    const git_oid *oid)
{
    char hash[41];
    hash[40] = '\0';
    git_oid_fmt(hash, oid);
    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "%s: %s", name, hash);
}

const git_oid *lookup_master_tree(git_repository *repo)
{
    int ret;
    git_reference *ref;
    const git_oid *commit_oid;
    const git_oid *tree_oid;
    git_commit *commit;

    ret = git_reference_lookup(&ref, repo, "refs/heads/master");
    if (ret) {
        printf("git_reference_lookup() error: %s\n", git_strerror(ret));
        return NULL;
    }
    if (git_reference_type(ref) != GIT_REF_OID) {
        perror("reference_type is not oid reference.");
        return NULL;
    }

    commit_oid = git_reference_oid(ref);

    ret = git_commit_lookup(&commit, repo, commit_oid);
    tree_oid = git_commit_tree_oid(commit);
    git_commit_close(commit);
    return tree_oid;
}

static int lookup_object_by_name(request_rec *r,
                                 git_repository *repo,
                                 const git_oid *tree_oid,
                                 const char *name,
                                 const git_oid **oid)
{
    const git_tree_entry *entry;
    int ret;
    git_tree *tree;
    char *extname;
    int type = WIKI_NOTFOUND;

    ret = git_tree_lookup(&tree, repo, tree_oid);
    extname = apr_pstrcat(r->pool, name, ".md", NULL);
    entry = git_tree_entry_byname(tree, extname);
    if (entry) {
        type = WIKI_MARKDOWN;
    }else{
        entry = git_tree_entry_byname(tree, name);
        if (entry) {
            int attr = git_tree_entry_attributes(entry);
            if(S_ISDIR(attr)){
                type = WIKI_DIR;
            }else{
                type = WIKI_FOUND;
            }
        }
    }

    git_tree_close(tree);

    if (entry == NULL) {
        return WIKI_NOTFOUND;
    }
    *oid = git_tree_entry_id(entry); // is this safe?
    return type;
}

static int lookup_object_oid(request_rec *r,
                             git_repository *repo,
                             const git_oid *master,
                             const char *path,
                             const git_oid **oid)
{
    const git_oid *object_oid;
    int type;
    char *saveptr = NULL;
    char *part = NULL;
    char *token = apr_pstrdup(r->pool, path);
    const git_oid *tree_oid;

    tree_oid = master;

    printf("path=%s\n", path);

    while((part = apr_strtok(token, "/", &saveptr)) != NULL){
/*
        if (*part == '\0') {
            printf("continue\n");
            continue;
        }
*/
        printf("part=%s\n", part);
        type = lookup_object_by_name(r, repo, tree_oid, part, &object_oid);
        if(type == WIKI_NOTFOUND) {
            return type;
        }else if (type == WIKI_DIR) {
            tree_oid = object_oid;
        }

        //log_oid(r, "oid", object_oid);

        token = NULL;
    }

    *oid = object_oid;
    return type;
}

char *ltrim(const char *base, const char *path)
{
    int i = 0;
    size_t base_len = strlen(base);
    //size_t path_len = strlen(path);

    for (i = 0; i < base_len; i++) {
        if (base[i] != path[i]) {
            continue;
        }
    }
    while (path[i] && path[i] == '/') {
        i++;
    }
    return (char *)(path + i);
}


/* The wiki handler */
static int wiki_handler(request_rec *r)
{
    wiki_conf *conf;
    git_repository *repo;
    const git_oid *tree_oid;
    char *path;

    const git_oid *oid;
    char hash[41];
    hash[40] = '\0';
    int ret;
    int type;

    Document *doc;

    if (strcmp(r->handler, "wiki")) {
        return DECLINED;
    }

    if (r->header_only) {
        return OK;
    }

    conf =
        (wiki_conf *) ap_get_module_config(r->per_dir_config,
                                           &wiki_module);

    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "filename=%s",
                  r->filename);
    if (conf->basepath) {
        path = ltrim(conf->basepath, r->parsed_uri.path);
    } else {
        path = r->parsed_uri.path + 1;
    }

    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "path=%s", path);
    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                  "r->content_type=%s", r->content_type);

    if (conf->repo == NULL) {
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                      "WikiRepository is not set.");
        return HTTP_INTERNAL_SERVER_ERROR;
    }
    ret = git_repository_open(&repo, conf->repo);
    if (ret) {
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                      "Cannot open git repository.(%s)", conf->repo);
        return HTTP_INTERNAL_SERVER_ERROR;
    }

    tree_oid = lookup_master_tree(repo);
    if (tree_oid == NULL) {
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                      "Not found master tree.");
        git_repository_free(repo);
    }

    type = lookup_object_oid(r, repo, tree_oid, path, &oid);
    if (type == WIKI_NOTFOUND) {
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r,
                      "Object is not found.");
        git_repository_free(repo);
        return HTTP_NOT_FOUND;
    } else if(type == WIKI_DIR) {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                      "Directory listing is not implement yet.");
        git_repository_free(repo);
        return HTTP_FORBIDDEN;
    } else if(type == WIKI_ERROR) {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                      "Error at lookup.");
        git_repository_free(repo);
        return HTTP_NOT_FOUND;
    }

    git_oid_fmt(hash, oid);
    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "object hash=%s", hash);

    const char *data;
    size_t size;

    git_odb *odb;
    odb = git_repository_database(repo);
    git_odb_object *odb_object;
    ret = git_odb_read(&odb_object, odb, oid);
    data = git_odb_object_data(odb_object);
    size = git_odb_object_size(odb_object);

    git_odb_object_close(odb_object);	// is this safe?

    if (type == WIKI_FOUND) {
        ap_rwrite(data, size, r);
    } else if(type == WIKI_MARKDOWN) {
        r->content_type = "text/html";
        doc = mkd_string(data, size, 0);
        if (doc == NULL) {
            ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                          "mkd_string() returned NULL\n");
            git_repository_free(repo);
            return HTTP_INTERNAL_SERVER_ERROR;
        }
        markdown_output(doc, r);
    } else {
        ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                      "Unknown Error.\n");
        git_repository_free(repo);
        return HTTP_INTERNAL_SERVER_ERROR;
    }

    git_repository_free(repo);
    return OK;
}

static void *wiki_config(apr_pool_t * p, char *dummy)
{
    wiki_conf *c = (wiki_conf *) apr_pcalloc(p, sizeof(wiki_conf));
    memset(c, 0, sizeof(wiki_conf));
    return (void *)c;
}

static const char *set_wiki_repo(cmd_parms * cmd, void *conf,
                                 const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    c->repo = arg;
    return NULL;
}

static const char *set_wiki_name(cmd_parms * cmd, void *conf,
                                 const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    c->name = arg;
    return NULL;
}

static const char *set_wiki_basepath(cmd_parms * cmd, void *conf,
                                     const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    c->basepath = arg;
    return NULL;
}

static const char *set_wiki_css(cmd_parms * cmd, void *conf,
                                const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    list_t *item = (list_t *) malloc(sizeof(list_t));
    item->data = arg;
    item->next = NULL;

    list_t *tail;
    if (c->css) {
        tail = c->css;
        while (tail->next)
            tail = (list_t *) tail->next;
        tail->next = (struct list_t *)item;
    } else {
        c->css = item;
    }
    return NULL;
}

static const char *set_wiki_header(cmd_parms * cmd, void *conf,
                                   const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    c->header = arg;
    return NULL;
}

static const char *set_wiki_footer(cmd_parms * cmd, void *conf,
                                   const char *arg)
{
    wiki_conf *c = (wiki_conf *) conf;
    c->footer = arg;
    return NULL;
}

static const command_rec wiki_cmds[] = {
    AP_INIT_TAKE1("WikiRepository", set_wiki_repo, NULL, OR_ALL,
                  "set Repository"),
    AP_INIT_TAKE1("WikiName", set_wiki_name, NULL, OR_ALL,
                  "set WikiName"),
    AP_INIT_TAKE1("WikiBasePath", set_wiki_basepath, NULL, OR_ALL,
                  "set Base Path"),

    AP_INIT_TAKE1("WikiCSS", set_wiki_css, NULL, OR_ALL,
                  "set CSS"),
    AP_INIT_TAKE1("WikiHeaderHtml", set_wiki_header, NULL, OR_ALL,
                  "set Header HTML"),
    AP_INIT_TAKE1("WikiFooterHtml", set_wiki_footer, NULL, OR_ALL,
                  "set Footer HTML"),
    {NULL}
};

static void wiki_register_hooks(apr_pool_t * p)
{
    ap_hook_handler(wiki_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA wiki_module = {
    STANDARD20_MODULE_STUFF,
    wiki_config,                /* create per-dir    config structures */
    NULL,                       /* merge  per-dir    config structures */
    NULL,                       /* create per-server config structures */
    NULL,                       /* merge  per-server config structures */
    wiki_cmds,                  /* table of config file commands       */
    wiki_register_hooks         /* register hooks                      */
};

/*
 * Local Variables:
 * tab-width: 4
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 * vim: sw=4 ts=4 sts=4 et
 */
